### ISSUE TITLE
Todo: Header component with no valid refs

### ISSUE THREAD

**Issue by pybalt** [inkua/maqueta-ong#12]
The header component [(see)](https://github.com/inkua/maqueta-ong/blob/5ee9119592f25a6abe31d757059712c0d4fffe3a/src/components/Header.jsx#L13) has no valid link references. We will need to fix this later once Routing is stablished.

```
<a class = "any link in the file">
href="#top"
</a>
`

**Comment by JuniorCalva40** [comment]
In the current branch main I can't find the header.jsx
