### ISSUE TITLE
Fix: Responsiveness

### ISSUE THREAD

**Issue by pybalt** [inkua/maqueta-ong#36]
![image](https://github.com/inkua/maqueta-ong/assets/96897286/32226c44-3792-4e00-908a-6bf5f1488a88)

**Comment by CMacxC** [comment]
I fix this problem

**Comment by pybalt** [comment]
I suggest you using calc() css function, and taking the width of the screen as param.

Otherwise you can also use a custom hook to calculate the width of each component
