### ISSUE TITLE
Bussiness logic: DATA handling

### ISSUE THREAD

**Issue by pybalt** [inkua/maqueta-ong#38]
Should we use a constant object where we hardcode the data, or should it be an algorythm that handles different json files?

## This decision is critic and will impact the user experience. (Another organizations)

**Comment by CMacxC** [comment]
In the moment in that I do the json file to put the information in the cards I though good idea, but I was trying to do with MDX files to make the cards. For exaple in Astrojs, can make a folder with MDX files and go through the files as if they were in an arrangement to make some cards, but I don't find information in NextJS Documentation.

How does this part impact the user experience?

**Comment by pybalt** [comment]
The client experience if you want to define them as that. I'm trying to make easier the work of other organizations when they use our template.

My idea is (telling it as a user storie):
_I'm about to launch my ong, I don't know much about technology._
- I want to fill information in some **site**, click a button and generate the site for my organization.

So the main issue is:
How we collect that data?
That site could be some json files (your method), or a single .ts file (my method).
I think we shouldn't use .ts because it can lead to syntax errors for them.

I was thinking more of some website to pregenerate the json files, copy and paste in this project and your page is ready to go.

**Comment by pybalt** [comment]
I think this is crucial because our basecode is growing and we have faced two opinioned ways of solving the same issue, which is wrong. We need to keep a standard. 

We must take a decision because this could lead to bugs//unreadable code.

**Comment by bairon-cano** [comment]
I think I agree and we must choose one of the two options. For me, the best one is in a JSON file, we could do the same as in the "ong.ts" file, with a styles property, another of pages and put the information in that JSON, so as not to have to make a different file to each page. Or I don't know what you think.

**Comment by bairon-cano** [comment]
maybe we could also make a page for the data to enter and we also generate the JSON when a button is pressed, I don't know, it could be a form and we could also include an "input type color" for the colors of the page. Or how do you plan to do it?

**Comment by pybalt** [comment]
I'm glad to see that we're on the same page. That's exactly what I was thinking on!. 😁

**Comment by bairon-cano** [comment]
Great! We could think about how to do it when we already have the whole page built, and we can continue for now with the JSON that you are creating, or do you plan to prioritize making that page first?

**Comment by pybalt** [comment]
I think we have to propose it to the design team. They'll have to make the decision. In the meantime, we continue building what they gave us.

**Comment by bairon-cano** [comment]
@CMacxC Could you tell that to the design team? Please

**Comment by CMacxC** [comment]
Sure, but to be sure, the question is whether you are going to design a page to make a JSON that fence filling the cards of the opinions?
